nota01 = input("Digite a nota: ")
nota02 = input("Digite a nota: ")
nota03 = input("Digite a nota: ")
nota04 = input("Digite a nota: ")
print(int(nota01) + int(nota02) + int(nota03) + int(nota04) / 3)